### ISSUE TITLE
ClassNotFoundException while bypassing ssl pinnings

### ISSUE THREAD

**Issue by sgs-97** [UCI-Networking-Group/OVRseen#5]
Hi,

I've been attempting to use the bypass_all_ssl_pinnings.sh script with several apps, but I'm encountering the same error across all of them. I added some print statements and console.log to both run_bypass_all_ssl_pinnings.py and bypass_all_ssl_pinnings.js, and here is the error I'm facing.

![Screenshot from 2024-09-24 15-41-28](https://github.com/user-attachments/assets/c45f949f-1aaf-440c-8245-bec36811423d)

I examined the classes.dex file in the unpacked game APK but was unable to locate the three classes (TrustManagerImpl, OkHTTP3, Appcelerator) within it.
Additionally, the DexPathList (/data/data/woosterGames.animalCompany/cache/frida6444013439652994082.dex) on the device is not accessible, so I can't verify whether the three classes are present. However, based on the error message, two of them (OKHttp3 and Appcelerator) seem to be missing.
Could you provide any details on how you added these classes to the apk?

**Comment by rtrimana** [comment]
Hi @sgs-97 , thank you very much for opening the issue.

From what you wrote above and also your screenshot, I believe the script did not find anything hookable from the app/game that you were trying it on. It saw the Unity version 2022.3.32f1. I am not sure if we already have that version in our Unity bundle as outlined in [step 3 here](https://github.com/UCI-Networking-Group/OVRseen/wiki/Traffic-Collection). Further, it just doesn't see the MbedTLS library, also Unreal, and the normal Android libraries, such as OKHttp3 and Appcelerator. The Android part is a universal script that contains FRIDA hooks for most known Android encryption libraries. These libraries are used by the application and compiled into an APK file, so I would say we don't add them into the APK as per your question.

The purpose of the script is to find any encryption libraries and bypass it, so we don't actually add anything to the APK. May I know which app/game that you are trying to run the script on?

**Comment by sgs-97** [comment]
Hi @rtrimana ,

I'm currently testing an app called Animal Company on Meta Quest pro. Even though the latest version of Frida is 16.5.2, I'm using frida-tools==10.4.1 and frida==15.0.8.

1. I checked the unity_so_files directory but couldn’t find the 2022.3.32f1 version. Is there a way to generate files for Unity versions that are unavailable which can also help me in future as I'm planning to test many apps?

2. Could you guide me on where to add mbedTLS library key file so the OVRseen can pick that file?

3. Until now I never tested Unreal based game. Do I need to provide any .so files for the unreal based game as well?

if OKHttp3 and Appcelerator are supposed to be included by default, I hope they’ll be available once the above issues are resolved.

**Comment by rtrimana** [comment]
Hi @sgs-97,

Right, on the Frida side, it is fine to use the older version. In fact, our scripts were tested using that version instead of the latest one.

1. For downloading new Unity versions, you can check the step 3 in https://github.com/UCI-Networking-Group/OVRseen/wiki/Traffic-Collection.

2. I think you misunderstood the process here. :) The mbedTLS library is not added into the APK/game/app file. OVRseen is supposed to look for that library if the APK/game/app uses it. The library is used when the developer develops and compiles their APK/game/app. So, it's not coming from us.

3. For any apps, we pretty much need the APK file that will be processed by the scripts. My recommendation is perhaps to first try the scripts with BeatSaber - Demo APK (see step 10 in https://github.com/UCI-Networking-Group/OVRseen/wiki/Traffic-Collection).

OKHttp3 and Appcelerator are usually used by Android apps/games, so they are not common in VR, except for a minority set of apps/games that are ported from Android or they happen to use Android libraries. In general, Unity and Unreal-based apps do not use those Android libraries AFAIK. In fact, Unity seems to use mbedTLS for encryption, not OKHttp3, Appcelerator and others.

The point of OVRseen is to find the library that is responsible for packet encryption and bypass the certificate validation process so that we can get access to the plaintext/unencrypted payload.

Hope this helps.

**Comment by sgs-97** [comment]
Hi @rtrimana ,

Thank you for your prompt response; it has really helped clarify things for me! 🙂

I have an additional question about the device trusting the Ant Monitor certificate. Does the JS Frida script that ensures trust for the Ant Monitor certificate also implicitly make all other user certificates on the device trusted? Or is it solely responsible for making the Ant Monitor certificate trusted?

**Comment by rtrimana** [comment]
Hi @sgs-97 ,

You are welcome! I am glad it was helpful. 🙂

To your question, I think it should be the former. We can replace AntMonitor and its certificate with any MiTM tool (and its certificate). The JS script is just bypassing the certificate validation function's checks and making sure that it always returns TRUE for any certificates. In other words, any certificate is a valid certificate: it is not limited to AntMonitor and its certificate.

**Comment by sgs-97** [comment]
Thanks a lot!
